### ISSUE TITLE
Problem with binomial model when running example code

### ISSUE THREAD

**Issue by joan-arau** [quantsbin/Quantsbin#2]
I ran this code from the example: 
import quantsbin.derivativepricing as qbdp

equity_p1 = qbdp.EqOption(option_type='Put', strike=50, expiry_date='20190721', expiry_type='European')
equity_p2 = qbdp.EqOption(option_type='Put', strike=50, expiry_date='20190721', expiry_type='American')

market1_parameters = {'spot0': 45
                     , 'pricing_date':'20180121'
                     , 'volatility':.25
                     , 'rf_rate':.05
                     , 'yield_div':0.02}

eq1_BSM_market1 = equity_p1.engine(model="BSM", **market1_parameters)
eq1_market1 = equity_p1.engine(model="Binomial", **market1_parameters)
eq2_market1 = equity_p2.engine(model="Binomial", **market1_parameters)

print("Value of eq1 under market 1 with BSM model is {}".format(eq1_BSM_market1.valuation()))
print("Value of eq1 under market 1 with Binomial model is {}".format(eq1_market1.valuation()))
print("Value of eq2 under market 1 with Binomial model is {}".format(eq2_market1.valuation()))

print("parms of eq1 under market 1 with BSM model is {}".format(eq1_BSM_market1.risk_parameters()))
print("parms of eq1 under market 1 with Binomial model is {}".format(eq1_market1.risk_parameters()))
print("parms of eq2 under market 1 with Binomial model is {}".format(eq2_market1.risk_parameters()))

BSM works fine but binomial gives the error:

Traceback (most recent call last):
    print("parms of eq1 under market 1 with Binomial model is {}".format(eq1_market1.risk_parameters()))
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/quantsbin/derivativepricing/engineconfig.py", line 66, in risk_parameters
    , delta_rf_conv=delta_rf_conv, delta_cost_yield=delta_cost_yield, **kwargs)
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/quantsbin/derivativepricing/engineconfig.py", line 79, in risk_parameters_num
    return ng.risk_parameters_num()
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/quantsbin/derivativepricing/numericalgreeks.py", line 70, in risk_parameters_num
    return {RiskParameter.DELTA.value: self.delta()
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/quantsbin/derivativepricing/numericalgreeks.py", line 55, in delta
    return self.degree_one(UnderlyingParameters.SPOT.value, self.delta_spot)
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/quantsbin/derivativepricing/numericalgreeks.py", line 44, in degree_one
    return (up_model.valuation() - down_model.valuation())/(2*(getattr(self._model, var)*change))
ZeroDivisionError: float division by zero

**Comment by quantsbin** [comment]
Hi Joan,
Thanks for raising the issue. 
We are calculating Numerical Greeks for Binomial model. And it takes the arguments for Change in spot price(delta_spot), Change in volatility(delta_vol), Change in risk-free rate(delta_rf_rate), Change in time(delta_time).
For now, these parameters are set to 0 by default. We will change these in our next release.
For your reference, I am changed your code a bit and it runs without any error.
Thanks!

import quantsbin.derivativepricing as qbdp

equity_p1 = qbdp.EqOption(option_type='Put', strike=50, expiry_date='20190721', expiry_type='European')
equity_p2 = qbdp.EqOption(option_type='Put', strike=50, expiry_date='20190721', expiry_type='American')

market1_parameters = {'spot0': 45,
                      'pricing_date': '20180121',
                      'volatility': .25,
                      'rf_rate': .05,
                      'yield_div': 0.02}

risk_parameters = {'delta_spot':0.02, 'delta_vol':0.02, 'delta_rf_rate':0.02,
                            'delta_time':1}

eq1_BSM_market1 = equity_p1.engine(model="BSM", **market1_parameters)
eq1_market1 = equity_p1.engine(model="Binomial", **market1_parameters)
eq2_market1 = equity_p2.engine(model="Binomial", **market1_parameters)

print("Value of eq1 under market 1 with BSM model is {}".format(eq1_BSM_market1.valuation()))
print("Value of eq1 under market 1 with Binomial model is {}".format(eq1_market1.valuation()))
print("Value of eq2 under market 1 with Binomial model is {}".format(eq2_market1.valuation()))

print("parms of eq1 under market 1 with BSM model is {}".format(eq1_BSM_market1.risk_parameters()))
print("parms of eq1 under market 1 with Binomial model is {}".format(eq1_market1.risk_parameters(**risk_parameters)))
print("parms of eq2 under market 1 with Binomial model is {}".format(eq2_market1.risk_parameters(**risk_parameters)))

**Comment by joan-arau** [comment]
Hello, Thank you for the quick reply!!
I am a little confused as to what values I should enter for these parameters in my real code so basically based on what assumption did you pick 0.02 for the delta parameters?

**Comment by quantsbin** [comment]
For model such as BSM, we have closed form solution for Greeks, but in case of numerical methods such as Binomial model to calculate Greeks we use bump and reset methodology i.e. We bump the underlying parameter and revalue the trade to calculate the sensitivity. The value 0.02 is delta by which you want to bump spot or rf or time (1 corresponding to 1 day for theta) to calculate corresponding sensitivity.
This value should be small to only consider the local impact and large enough to ignore impact of any noise due to calculation methodology.
