### ISSUE TITLE
spline method

### ISSUE THREAD

**Issue by WladimirOstrovsky** [quantsbin/Quantsbin#4]
Hi there,

its not a real issue I would say but if you use the current scipy package rather than 1.0 (as mentioned in the requirements) the spline method will not be found. It relates to the refactoring from spline to UnivariateSpline.

To solve this rename all occurences of '**spline**' to '**UnivariateSpline**'. 

Disclaimer: I am not sure if all the functions will work with this change and whether the behaviour is as expected.

Happy coding
W

**Comment by quantsbin** [comment]
Have merged your changees. Will do throrough testing in coming weeks.
