### ISSUE TITLE
risk parameters do not work when pricing date and expiry date of an instrument is same

### ISSUE THREAD

**Issue by raiak82** [quantsbin/Quantsbin#6]
raise Exception("Pricing date should be less than expiry of instrument")

Exception: Pricing date should be less than expiry of instrument

**Comment by quantsbin** [comment]
Currently, the package is designed to capture end-of-day price and risk, hence on the day of expiry you have no risk and value of the option could be derived as intrinsic value.

I will try to update the package to give an option to capture interday risk and price i.e. considering the fraction of days while calculating time to expiry.
